# Generated by Django 2.1.2 on 2018-11-09 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20181109_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-id'], 'permissions': (('can_add_mod_del_authors', 'Add, modify or delete authors'),)},
        ),
    ]
